### PR TITLE
Try to run a headless app with swiftshader

### PR DESCRIPTION
**Pull request by hevrard**

### CODE REVIEW

**Comment by hevrard** [comment]
@AWoloszyn agreed, I'm just pushing binaries to try things out in this temporary PR, the final version will pull from other places, e.g. https://github.com/google/gfbuild-swiftshader/releases

**Comment by hevrard** [comment]
Trying to run the sample app using swiftshader under xvfb, it segfaults with:

```
/usr/lib/x86_64-linux-gnu/libxcb.so.1(xcb_setup_vendor_end+0x0)[0x7f2cb2756730]
/usr/lib/x86_64-linux-gnu/libxcb.so.1(xcb_setup_pixmap_formats_iterator+0x9)[0x7f2cb2756789]
/usr/lib/x86_64-linux-gnu/libxcb.so.1(xcb_setup_roots_iterator+0x9)[0x7f2cb27567c9]
/proc/self/cwd/cmd/vulkan_sample/main.cpp:300(_Z18CreateNativeWindowv)[0x40149c]
/proc/self/cwd/cmd/vulkan_sample/main.cpp:385(main)[0x4018b9]
```

@chrisforbes @AWoloszyn any idea what could be wrong there?

**Comment by AWoloszyn** [comment]
Maybe try with `-extension GLX` it might work?

**Comment by hevrard** [comment]
closing for now, to investigate later

**Pull request closed without merging**
