### PR TITLE
Update Kokoro script Bazel version to 1.0.0

### PR DESCRIPTION
**Pull request by hevrard**

### CODE REVIEW

**Comment by hevrard** [comment]
Part of fixing #3235

**Comment by hevrard** [comment]
Rebase on master, which currently builds fine on my Linux desktop with Bazel 1.0.0.
This kokoro run should build fine at least on Linux.

**Comment by hevrard** [comment]
The kokoro build error is related to aapt / aapt2:

```
SEVERE: Unexpected
com.google.devtools.build.android.DeserializationException: aapt2 version mismatch.
	at com.google.devtools.build.android.AndroidCompiledDataDeserializer.read(AndroidCompiledDataDeserializer.java:690)
	at com.google.devtools.build.android.SerializedAndroidData.deserialize(SerializedAndroidData.java:105)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:255)
	at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:85)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:102)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:237)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:198)
Caused by: com.google.devtools.build.android.DeserializationException: Unexpected tag for resourceType 1919159562 expected 0 or 1 in gapidapk/android/app/src/main/res/drawable-xxxhdpi_logo.png.flat.
 Last known good values:
	magicNumber 1414545729 (is 1)
	formatVersion 1 (is 136)
	numberOfEntries 1 (is 0)
	... 7 more
```

I cannot reproduce this issue on my desktop, even when trying to repro a similar environment to Kokoro.

After chatting with Bazelbuild folks, it sounds like bazel 1.0.0 is assuming to use aapt2 and the `--android_aapt=aapt` is not very reliable. Sounds like we had better bite the bullet and use aapt2.

**Comment by hevrard** [comment]
We're now passing all builds but Windows ones.

The remaining issue is actually #2914

**Comment by hevrard** [comment]
Windows build fail with all versions of bazel from 0.27. Changelog for this version has the following comment which seems relevant:
> Repository containing autoconfigured C++ toolchain @local_config_cc has been split in 2 - see local_config_cc_toolchains.

But this `local_config_cc_toolchains` seems to be undocumented.

**Comment by hevrard** [comment]
Hints from Bazel folks: https://github.com/bazelbuild/bazel/issues/10086#issuecomment-547514529

**Comment by pmuetschard** [comment]
Documentation is here: https://docs.bazel.build/versions/master/cc-toolchain-config-reference.html

We need to rework our toolchain setup to match.

**Comment by johnplate** [comment]
Made redundant by #3432

**Pull request closed without merging**
