### PR TITLE
Android related fixes to the Vulkan sample.

### PR DESCRIPTION
**Pull request by pmuetschard**
- Don't ever use mailbox mode, always use the guaranteed FIFO mode.
 - On Android, always use 3 swapchain images.

### CODE REVIEW

**Comment by AWoloszyn** [comment]
For Android we should still check minimagecount for the swapchain. We can default to 3 but if min is 4 we should respect that.

**Comment by AWoloszyn** [comment]
Also, out of curiosity why not mailbox?

**Comment by pmuetschard** [comment]
> For Android we should still check minimagecount for the swapchain. We can default to 3 but if min is 4 we should respect that.

Done.

> Also, out of curiosity why not mailbox?

Even with the display running at 90Hz, we were rendering the cube 3-4 times per frame. This is a waste.

**Comment by chrisforbes** [comment]
I have 2 reasons to prefer fifo here:
- mailbox is not guaranteed to be available
- when we get to validating the SF events producer, fifo is far less
chaotic (frames are consumed in order, and none get dropped)

**Comment by AWoloszyn** [comment]
> I have 2 reasons to prefer fifo here: - mailbox is not guaranteed to be available - when we get to validating the SF events producer, fifo is far less chaotic (frames are consumed in order, and none get dropped)

- We don't explicitly choose Mailbox, we choose the first provided mode.
- FIFO is less chaotic, but using it in the sample may prevent us from finding some bugs. It takes a non-trivial amount of work for us to handle out-of-order swapchain images etc, and having tests is useful.

That being said, I totally understand for this type of sample switching off, but we do lose some normal coverage, but that code-path is already fairly well tested anyway.

I don't mind having this.

**Comment by chrisforbes** [comment]
For test coverage I completely agree with you -- this sample is being used for device validation though, so ought to be as predictable as possible

**Pull request merged**
