### PR TITLE
Don't crash if an invalid texture is attached to an FB.

### PR DESCRIPTION
**Pull request by pmuetschard**

### CODE REVIEW

**Comment by pmuetschard** [comment]
It happens in the APK we've been looking at. I presume in this specific instance it's because of shared contexts. Either way, we should avoid having gapis crash on bad data.

**Comment by dsrbecky** [comment]
Yeah, but this is not exactly bad data.
We managed to get ourselves into inconsistent internal state.  That should not happen.
I will see if I can reproduce it myself....

**Comment by dsrbecky** [comment]
Does this #220 fix it?

**Comment by pmuetschard** [comment]
> Does #220 fix it?

No it does not :(
```
W20170405-152443711 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
W20170405-152443712   panic: Panic at atom 421: runtime error: invalid memory address or nil pointer dereference
W20170405-152443712 [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x13bb415]
W20170405-152443712 
W20170405-152443713 goroutine 79 [running]:
W20170405-152443713 github.com/google/gapid/gapis/resolve.(*FramebufferChangesResolvable).Resolve.func1(0xc421e83de8)
W20170405-152443713   /usr/local/google/work/gapid/src/github.com/google/gapid/gapis/resolve/framebuffer_changes.go:51 +0x121
W20170405-152443714 panic(0x20e8320, 0x3cc9540)
W20170405-152443714   /usr/local/google/work/gapid/go/src/runtime/panic.go:489 +0x2cf
W20170405-152443714 github.com/google/gapid/gapis/gfxapi/gles.(*State).getFramebufferAttachmentInfo(0xc42094d880, 0xc400000002, 0xc421e83d40, 0xc4203e8ab8, 0x0, 0x3ce1c80, 0xc42041e6e0)
W20170405-152443714   /usr/local/google/work/gapid/src/github.com/google/gapid/gapis/gfxapi/gles/state.go:69 +0x3f5
W20170405-152443714 github.com/google/gapid/gapis/gfxapi/gles.api.GetFramebufferAttachmentInfo(0xc4228bad90, 0x2, 0xc421e83f10, 0xc421e83ef0, 0x19, 0xc42041e600)
W20170405-152443715   /usr/local/google/work/gapid/src/github.com/google/gapid/gapis/gfxapi/gles/gles.go:32 +0xc6
W20170405-152443715 github.com/google/gapid/gapis/gfxapi/gles.(*api).GetFramebufferAttachmentInfo(0x3e760b8, 0xc4228bad90, 0x2, 0x0, 0x0, 0x3ce1c80, 0xc42041e6e0)
W20170405-152443715   <autogenerated>:2415 +0x57
W20170405-152443715 github.com/google/gapid/gapis/resolve.(*FramebufferChangesResolvable).Resolve(0xc421ffc040, 0x3d7b300, 0xc421c6f7d0, 0x0, 0x0, 0x0, 0x0)
W20170405-152443717   /usr/local/google/work/gapid/src/github.com/google/gapid/gapis/resolve/framebuffer_changes.go:78 +0x709
W20170405-152443717 github.com/google/gapid/gapis/database.(*memory).resolve.func1(0x3d17000, 0xc421ffc040, 0xc42207a1e0, 0xc420648120, 0x3d7b240, 0xc42094cc00)
W20170405-152443718   /usr/local/google/work/gapid/src/github.com/google/gapid/gapis/database/memory.go:123 +0x4e
W20170405-152443719 created by github.com/google/gapid/gapis/database.(*memory).resolve
W20170405-152443719   /usr/local/google/work/gapid/src/github.com/google/gapid/gapis/database/memory.go:133 +0x601
```

**Comment by pmuetschard** [comment]
I think the reason being that the texture is deleted before the framebuffer:

```
000414 glGenFramebuffers(Count: 1, Framebuffers: 0xd472a528)
000415 glBindFramebuffer(Target: GL_FRAMEBUFFER, Framebuffer: 1)
000416 glGenTextures(Count: 1, Textures: 0xd472a524)
000417 glBindTexture(Target: GL_TEXTURE_2D, Texture: 1)
000418 glTexImage2D(Target: GL_TEXTURE_2D, Level: 0, Internalformat: 32993, Width: 256, Height: 256, Border: 0, Format: GL_BGRA_EXT, Type: GL_UNSIGNED_BYTE, Data: 0)
000419 glFramebufferTexture2D(FramebufferTarget: GL_FRAMEBUFFER, FramebufferAttachment: GL_COLOR_ATTACHMENT0, TextureTarget: GL_TEXTURE_2D, Texture: 1, Level: 0)
000420 glCheckFramebufferStatus(Target: GL_FRAMEBUFFER)-> GL_FRAMEBUFFER_COMPLETE
000421 glDeleteTextures(Count: 1, Textures: 0xd472a524)
000422 glDeleteFramebuffers(Count: 1, Framebuffers: 0xd472a528)
```

**Comment by dsrbecky** [comment]
Ah - fair enough.
That should be handled in the API as well, but I am not feeling up to that now.
Feel free to commit this.

**Comment by ben-clayton** [comment]
> That should be handled in the API as well, but I am not feeling up to that now.

I believe this is mostly tracked by https://github.com/google/gapid/issues/18

**Pull request merged**
