### PR TITLE
Fix sparse binding for Vulkan DCE

### LINKED ISSUE #1291: Vulkan DCE does not handle sparse binding

### PR DESCRIPTION
**Pull request by Qining**
Fix #1291

### CODE REVIEW

**Comment by Qining** [comment]
Still WIP. So far only have the 'list' based resource binding added in Vulkan's DCE.

**Comment by Qining** [comment]
Ready for review. This CL fixes the crash/replay failure when sparse bindings are used. Note that sparse residency is still not supported yet.

**Comment by ben-clayton** [comment]
How critical is this fix? Should we stall 0.9 to get this in? How confident are you that it doesn't cause more issues than it fixes?

**Comment by Qining** [comment]
This is not that critical, since we didn't see people actually using sparse binding yet, so generally gapid will not crash. And I'm testing it with some samples now.

**Pull request merged**
