### PR TITLE
Update suggested JRE link to OpenJDK

### PR DESCRIPTION
**Pull request by hevrard**
b/145703511

Oracle JDK now requires an Oracle account, OpenJDK is easier to obtain.

### CODE REVIEW

**Comment by AWoloszyn** [comment]
Strange, I have been building with openjdk-11 for a long time now

**Comment by johnplate** [comment]
On Windows? I didn't try OpenJDK 11, but the Android SDK sdkmanager didn't work with JDK 11 + 13

**Comment by johnplate** [comment]
The text is clear now, thanks. Did anyone recently try to compile GAPID with OpenJDK 8 on the three supported platforms?

**Comment by hevrard** [comment]
@johnplate I've just confirmed it builds fine on MacOS with the JDK 8-Hotspot obtained via adoptopenjdk. Can you review again?

**Pull request merged**
