### PR TITLE
Prefetch phydev properties

### PR DESCRIPTION
**Pull request by Qining**
Fix Issue #1311

### CODE REVIEW

**Comment by Qining** [comment]
I think this might not work correctly in the case of multiple GPU yet. But it should fix #1311 for single-GPU case now. Working on a commit to make sure the physical device order is correct.

**Comment by Qining** [comment]
Enumeration order is now recorded in the state block when `prefetchPhysicalDeviceProperties()` is called.

**Comment by AWoloszyn** [comment]
So the actual enumeration order is not important iirc. As long as, during replay, we only call ReplayEnumeratePhysicalDevices, since nothing depends on the actual order that things were returned in. the only thing that matters is preserving the mapping between vkenumeratephysicaldevices and the device/Vendor ID

**Comment by Qining** [comment]
@AWoloszyn My understanding is that we need to make sure the order of vender|deviceIDs for the `replayEnumeratePhysicalDevices` must match with the physical device enumeration order in the trace side. Is this right?

**Comment by AWoloszyn** [comment]
IT doesn't have to match the device enumeration ORDER specifically, but the 
VkPhysicalDevice -> vendor/deviceID     must be correct.

**Comment by Qining** [comment]
@AWoloszyn Thanks for the instruction. So currently the code is not working correctly as the order might be different between the Vender|DeviceIDs and the physical devices sent to the `replayEnumeratePhysicalDevices`. I will work on a fix for this.

**Comment by Qining** [comment]
@AWoloszyn finally I understand why we just need to make sure those two arrays have to match. CL at: https://github.com/google/gapid/pull/1335

**Pull request merged**
