### PR TITLE
Check if there is a bound texture unit before getting it's id.

### LINKED ISSUE #2623: The gapis server has exited with an error code of: 2
GAPID Version: 1.3.1:44c6681a66df5e84e2cd8e56fbd8f968be2fafd6
OS: windows 10 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: 
--- *initialcmds.InitialCmdsResolvable ---
 capture:<ID:<data:"8>,\342\205\376v#\271\031\301:(zr\221\322g\225\274" > > 
 Store():
  gapis/database/database.go:55  github.com/google/gapid/gapis/database.Build
  gapis/resolve/initialcmds/initial_commands.go:40  github.com/google/gapid/gapis/resolve/initialcmds.InitialCommands
  gapis/resolve/resources.go:58  github.com/google/gapid/gapis/resolve.(*ResourcesResolvable).Resolve
  gapis/database/memory.go:134  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:238  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:59  github.com/google/gapid/gapis/database.Build
  gapis/resolve/initialcmds/initial_commands.go:40  github.com/google/gapid/gapis/resolve/initialcmds.InitialCommands
  gapis/resolve/resources.go:58  github.com/google/gapid/gapis/resolve.(*ResourcesResolvable).Resolve
  gapis/database/memory.go:134  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:238  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.ResourcesResolvable ---
 capture:<ID:<data:"8>,\342\205\376v#\271\031\301:(zr\221\322g\225\274" > > config:<replay_device:<ID:<data:"3\363\352\337\035\010FuV\004\323\346\010\377\200\032}\202\007\214" > > > 
 Store():
  gapis/database/database.go:55  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:340  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:134  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:238  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:59  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:340  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:134  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:238  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.GetResolvable ---
 path:<resources:<capture:<ID:<data:"8>,\342\205\376v#\271\031\301:(zr\221\322g\225\274" > > > > config:<replay_device:<ID:<data:"3\363\352\337\035\010FuV\004\323\346\010\377\200\032}\202\007\214" > > > 
 Store():
  gapis/database/database.go:55  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:388  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:197  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:10555  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:10557  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:982  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1208  google.golang.org/grpc.(*Server).handleStream

 Build() #0:
  gapis/database/database.go:59  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:388  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:197  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:10555  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:10557  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:982  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1208  google.golang.org/grpc.(*Server).handleStream
 [recovered]
	panic: 
--- *initialcmds.InitialCmdsResolvable ---
 capture:<ID:<data:"8>,\342\205\376v#\271\031\301:(zr\221\322g\225\274" > > 
 Store():
  gapis/database/database.go:55  github.com/google/gapid/gapis/database.Build
  gapis/resolve/initialcmds/initial_commands.go:40  github.com/google/gapid/gapis/resolve/initialcmds.InitialCommands
  gapis/resolve/resources.go:58  github.com/google/gapid/gapis/resolve.(*ResourcesResolvable).Resolve
  gapis/database/memory.go:134  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:238  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:59  github.com/google/gapid/gapis/database.Build
  gapis/resolve/initialcmds/initial_commands.go:40  github.com/google/gapid/gapis/resolve/initialcmds.InitialCommands
  gapis/resolve/resources.go:58  github.com/google/gapid/gapis/resolve.(*ResourcesResolvable).Resolve
  gapis/database/memory.go:134  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:238  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.ResourcesResolvable ---
 capture:<ID:<data:"8>,\342\205\376v#\271\031\301:(zr\221\322g\225\274" > > config:<replay_device:<ID:<data:"3\363\352\337\035\010FuV\004\323\346\010\377\200\032}\202\007\214" > > > 
 Store():
  gapis/database/database.go:55  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:340  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:134  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:238  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:59  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:340  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:134  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:238  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.GetResolvable ---
 path:<resources:<capture:<ID:<data:"8>,\342\205\376v#\271\031\301:(zr\221\322g\225\274" > > > > config:<replay_device:<ID:<data:"3\363\352\337\035\010FuV\004\323\346\010\377\200\032}\202\007\214" > > > 
 Store():
  gapis/database/database.go:55  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:388  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:197  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:10555  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:10557  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:982  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1208  google.golang.org/grpc.(*Server).handleStream

 Build() #0:
  gapis/database/database.go:59  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:388  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:197  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:10555  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:10557  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:982  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1208  google.golang.org/grpc.(*Server).handleStream

[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1c98fbd]

goroutine 667 [running]:
github.com/google/gapid/core/app/crash.Crash(0x50e68c0, 0xc010ae94c0)
	core/app/crash/crash.go:89 +0xae
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x59
panic(0x50e68c0, 0xc010ae94c0)
	GOROOT/src/runtime/panic.go:513 +0x1c7
github.com/google/gapid/gapis/database.(*memory).resolvePanicHandler(0xc0002285c0, 0x62ea020, 0xc00fc7d950)
	gapis/database/debug.go:106 +0x7b6
panic(0x5286860, 0x441a3b0)
	GOROOT/src/runtime/panic.go:513 +0x1c7
github.com/google/gapid/gapis/api/gles.TextureUnitʳ.ID(...)
	bazel-out/x64_windows-opt/genfiles/gapis/api/gles/api.go:37514
github.com/google/gapid/gapis/api/gles.(*stateBuilder).contextObjectPostEGLImage(0xc013f36500, 0x62ea020, 0xc00fc7da40, 0xcfa767c0, 0xc011d78d20, 0xe90a)
	gapis/api/gles/state_builder.go:493 +0xddd
github.com/google/gapid/gapis/api/gles.API.RebuildState(0x62ea020, 0xc00fc7da40, 0xc0001ebc00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	gapis/api/gles/state_builder.go:102 +0x5dc
github.com/google/gapid/gapis/resolve/initialcmds.(*InitialCmdsResolvable).Resolve(0xc00fc7d860, 0x62ea020, 0xc00fc7da40, 0xc00fc7da40, 0xc0003edf18, 0x2, 0x2)
	gapis/resolve/initialcmds/initial_commands.go:62 +0x1e8
github.com/google/gapid/gapis/database.(*record).resolve(0xc00c9b6180, 0x62ea020, 0xc00fc7da40, 0x0, 0x0)
	gapis/database/memory.go:134 +0x22f
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
	gapis/database/memory.go:238 +0xd3
github.com/google/gapid/core/app/crash.Go.func1(0xc00fc7d8f0)
	core/app/crash/crash.go:65 +0x4a
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x46

---------------------------------------------------------------------------------------------

Device: Samsung Galaxy J7 Pro
OpenglES 3 application
capturing in the middle

### PR DESCRIPTION
**Pull request by AWoloszyn**
Fixes #2623.

### CODE REVIEW

**Comment by AWoloszyn** [comment]
I thought that might be the case. So I didn't want to continue.
Is there a texture unit bound if we have NEVER had one bound in the first place?

**Comment by pmuetschard** [comment]
Yes, there is a default texture unit (unit 0) which should be bound when the context is created.

**Comment by pmuetschard** [comment]
Are you actually working on this @AWoloszyn, or should we just close it?

**Comment by pau-baiget** [comment]
Ping @AWoloszyn

**Comment by AWoloszyn** [comment]
Sorry, I missed @pmuetschard's message and this fell off my radar. I have no plans on continuing to work on this, because I don't have enough context. I will close this PR.

**Pull request closed without merging**
