### PR TITLE
Virt swapchain threading fix

### PR DESCRIPTION
**Pull request by purvisa-at-google-com**
Sorry the Presubmit won't pass. I can't get clang-format to behave on my mac!

### CODE REVIEW

**Comment by AWoloszyn** [comment]
Seems fine with me, although if you are going to submit this apart from the Mac stuff, please remove that change from this MR.

**Comment by AWoloszyn** [comment]
Also obviously fix your formatting.

**Comment by RenfengLiu** [comment]
Just curious, what is the problem being fixed here?

**Comment by purvisa-at-google-com** [comment]
deadlock

**Comment by purvisa-at-google-com** [comment]
> Just curious, what is the problem being fixed here?

Deadlock on my laptop

**Pull request merged**
