### PR TITLE
Allow resolving of "hidden" commands to tree nodes.

### PR DESCRIPTION
**Pull request by pmuetschard**
See #1063

### CODE REVIEW

**Comment by ben-clayton** [comment]
I'm sure we must have had a face-to-face discussion about this, but I can't remember the outcome.
Do you still want this change?

**Comment by pau-baiget** [comment]
@pmuetschard @ben-clayton do we still want to merge this PR?

**Comment by AWoloszyn** [comment]
I think this is broken now anyway. I believe we are ALWAYS showing hidden nodes, which we should fix.

**Comment by pmuetschard** [comment]
I think with Q, we will no longer have nested calls (yay) and this is not that important, so closing it.

For reference: this was to fix an issue where the "goto command" UI action would fail, if an ID of a nested command was entered by the user. Since we do show those IDs in the UI, we should allow the user to "goto" them.

**Pull request closed without merging**
