### PR TITLE
Add tooltips for Enums in Pipeline View

### PR DESCRIPTION
**Pull request by hliatis**
Bug: 148873707

### CODE REVIEW

**Comment by johnplate** [comment]
Looks good overall, but a few comments/questions:
- Is there an associated buganizer task?
- Which enums are supposed to be covered by this PR? During my test only most KVP enums worked, but none in tables (on Windows, didn't test on Linux yet).
- The Cull Mode enum in Rasterization State did not work.

**Comment by hliatis** [comment]
Cull Mode is actually not a Vulkan enum but a bitfield (for reasons). I'll look into it.

**Comment by johnplate** [comment]
VkCullModeFlagBits is an enum that is used as bit field. As the existing four enums cover all possible bit combinations, we can simply see it as enum.

**Comment by hliatis** [comment]
It's sent to the client as a bitfield. The plumbing for bitfields is different from simple enums. I am looking into a solution now so that it can handle other, more "pure" bitfields as well

**Comment by hliatis** [comment]
For bitfields, the UI displays a truncated name separated by '|' (except for colors, where there is no separator). 

Would you be okay with a long tooltip where it's the longer names separated by '|'?

**Comment by johnplate** [comment]
As the client receives it as bitfield, I think we can leave the cull mode as is for now.

**Comment by hliatis** [comment]
I mean, I have the most basic solution where I show all the bit flags used separated by a |. The tip can be long for something like using RGBA bits in a color bitfield. Shall I push it?

**Comment by johnplate** [comment]
Please don't forget to answer this:
> * Which enums are supposed to be covered by this PR? During my test only most KVP enums worked, but none in tables (on Windows, didn't test on Linux yet).

**Comment by hliatis** [comment]
All enums, including tables. I am not sure what is going on there. I am using SWT's standard way of doing this.

**Pull request closed without merging**
