### PR TITLE
Fix missing panic messages

### PR DESCRIPTION
**Pull request by ben-clayton**

### CODE REVIEW

**Comment by AWoloszyn** [comment]
It looks like you may have missed one.
```
gapid/test/robot/lingo/examples/cstcalc/main.go:116:
         have (context.Context, string)
	want (context.Context, bool, string, ...interface {})
```

**Comment by ben-clayton** [comment]
> It looks like you may have missed one.

Yeah - I don't know what's going on here. After I pushed this, I saw a delta appear, and went to push it again, and it disappeared. :/
I'll guess I'll try it again!

**Comment by ben-clayton** [comment]
Mystery solved - `main.go` is a generated file. Doh!

**Comment by ben-clayton** [comment]
Looks like the windows build failed due to a random kokoro issue.

**Pull request merged**
