### PR TITLE
Add device flags to run GPU profiling validation on specific devices.

### PR DESCRIPTION
**Pull request by lpy**
BUG: b/138717619
TesT: bazel run gapit -- validate_gpu_profiling --serial SERIAL_NUMBER

### CODE REVIEW

**Comment by lpy** [comment]
We don't really need everything in `DeviceFlags`, besides the `Os` filed in `DeviceFlags` conflicts with the `OS` filed we have

**Comment by lpy** [comment]
Comment addressed, ptal :)

**Comment by AWoloszyn** [comment]
Thanks!

**Comment by lpy** [comment]
I should have seen there's a `filterDevices` function that I can just use

**Pull request merged**
