### PR TITLE
Recognize more Android versions.

### PR DESCRIPTION
**Pull request by lpy**
BUG: N/A
Test: N/A

### CODE REVIEW

**Comment by lpy** [comment]
PTAL

It's fine if this patch won't be accepted, just try to go through the GAPID workflow

**Comment by lpy** [comment]
One question, do I need to squash all commits into one before merge or will the bot do that for me?

**Comment by hevrard** [comment]
> One question, do I need to squash all commits into one before merge or will the bot do that for me?

The GitHub interface lets you do a "Squash and merge" action once the PR is approved.

Thanks for this fix!

Can you please mirror this change here (and add missing versions):
https://github.com/google/gapid/blob/master/core/os/device/android.go
https://github.com/google/gapid/blob/master/core/os/device/android_test.go

**Comment by lpy** [comment]
Thanks, ptal!

**Comment by hevrard** [comment]
You can use the "Reviewers" section in GitHub UI, on the PR page on the right, to explicitly ask for  reviews.

Thanks for this fix, I let you do the squash and merge. Please make sure to tidy up the commit message if need be.

**Comment by lpy** [comment]
Looks like I don't have permission to merge it, I don't have the merge button ¯\_(ツ)_/¯

**Comment by AWoloszyn** [comment]
Should work now.

**Pull request merged**
