### PR TITLE
gapic: Add various caches to reduce loading times of images.

### PR DESCRIPTION
**Pull request by ben-clayton**
Cache the unboxing of byte arrays so that we don’t end up with a different array for each call to Pods.getBytes().

Add comparable logic to ArrayImage.

Fixes: #655

### CODE REVIEW

**Comment by ben-clayton** [comment]
I've reworked this CL to remove the enormous cache in `FetchedImage`.

**Comment by pmuetschard** [comment]
Sorry, i guess we got our wires crossed here.. I thought I was going to look into this. I just saw this a few minutes ago, finishing up #1361. I've added the memory leak fix there as well.

**Comment by ben-clayton** [comment]
I tried to lighten your load a little. I did put this up for review 2 days ago :)

**Comment by pmuetschard** [comment]
I've merged #1361.

**Pull request closed without merging**
