### PR TITLE
Shared context

### PR DESCRIPTION
**Pull request by dsrbecky**
Still needs testing..

### CODE REVIEW

**Comment by ben-clayton** [comment]
Is this ready for reviewing?

**Comment by dsrbecky** [comment]
Feel free to review it, however there are other things (gapir) that are preventing me from fully testing it.

**Comment by dsrbecky** [comment]
I would say it is ready for review.
I do not think any remaining issues that I have are related to context sharing.
The main deficiency is lack of Mac&Window support as I do not have a way to test it.

**Comment by dsrbecky** [comment]
Fixed our integration tests and added test for shared contexts.

**Comment by ben-clayton** [comment]
Your parts LGTM.

**Comment by dsrbecky** [comment]
LGTM for your commits

**Pull request merged**
